#!/bin/bash

#single data sets for studies with disgenet information available
#python prepareDataset.py --project "TCGA-GBM"  --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-THCA" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-LAML" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-HNSC" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-LUAD" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-UCEC" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-KIRC" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#python prepareDataset.py --project "TCGA-SARC" "TCGA-GBM" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"

#single data sets for studies with no disgenet information available
#python prepareDataset.py --project "TCGA-PRAD" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-OV" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-COAD" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-LUSC" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-BRCA" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-STAD" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"
#python prepareDataset.py --project "TCGA-CESC" "TCGA-PAAD" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts" --sample_types "TP"

#all studies with some disgenet information available
#python prepareDataset.py --project "TCGA-GBM" "TCGA-THCA" "TCGA-LAML" "TCGA-HNSC" "TCGA-LUAD" "TCGA-UCEC" "TCGA-KIRC" "TCGA-SARC" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
#all studies with no disgenet information available
#python prepareDataset.py --project "TCGA-PRAD" "TCGA-OV" "TCGA-COAD" "TCGA-LUSC" "TCGA-BRCA" "TCGA-PAAD" "TCGA-STAD" "TCGA-CESC" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"

#all good and bad studies
python prepareDataset.py --project "TCGA-GBM" "TCGA-THCA" "TCGA-LAML" "TCGA-HNSC" "TCGA-LUAD" "TCGA-UCEC" "TCGA-KIRC" "TCGA-SARC" "TCGA-PRAD" "TCGA-OV" "TCGA-COAD" "TCGA-LUSC" "TCGA-BRCA" "TCGA-PAAD" "TCGA-STAD" "TCGA-CESC" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"

#prepare GTEx-Associated Dataset - primary set
#python prepareDataset.py --project "TCGA-PRAD" "TCGA-OV" "TCGA-COAD" "TCGA-BRCA" "TCGA-STAD" "TCGA-CESC" "TCGA-KIRC" "TCGA-BLCA" "TCGA-THCA" "TCGA-ESCA" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"

#prepare GTEx-Associated Dataset - extended set
#python prepareDataset.py --project "TCGA-PRAD" "TCGA-OV" "TCGA-COAD" "TCGA-BRCA" "TCGA-STAD" "TCGA-CESC" "TCGA-KIRC" "TCGA-BLCA" "TCGA-THCA" "TCGA-ESCA" "TCGA-LUSC" "TCGA-GBM" "TCGA-LUAD" "TCGA-UCEC" "TCGA-SARC" "TCGA-PCPG" "TCGA-ACC" "TCGA-KICH" "TCGA-UCS" --data_category "Transcriptome Profiling" --data_type "Gene Expression Quantification" --workflow "HTSeq - Counts"
